on:
    - push
    - pull_request

jobs:
    lint-and-build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
        defaults:
            run:
                working-directory: ./backend
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Run linter on backend
              run: pnpm run lint
            - name: run backend tests
              run: pnpm test
